# Generated by Django 6.0.2 on 2026-02-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pattern_type', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly')], default='weekly', max_length=10)),
                ('mon_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('tue_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('wed_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('thu_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fri_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sat_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sun_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mon_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('tue_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('wed_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('thu_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fri_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sat_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sun_hours_week_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mon_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('tue_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('wed_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('thu_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fri_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sat_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sun_hours_week_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('biweekly_start_date', models.DateField(blank=True, help_text='Date when Week A starts (for bi-weekly patterns)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner_name', models.CharField(max_length=200)),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'cleaner_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.company')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours', to='timesheet.timesheet')),
            ],
            options={
                'verbose_name_plural': 'Extra Hours',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.company')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheet.timesheet')),
            ],
            options={
                'verbose_name_plural': 'Timesheet Entries',
            },
        ),
    ]
